package com.mav.day1;

import com.mav.day1.Order;

public interface OrderMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Wed Nov 01 23:10:42 CST 2017
	 */
	int deleteByPrimaryKey(Integer orderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Wed Nov 01 23:10:42 CST 2017
	 */
	int insert(Order record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Wed Nov 01 23:10:42 CST 2017
	 */
	int insertSelective(Order record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Wed Nov 01 23:10:42 CST 2017
	 */
	Order selectByPrimaryKey(Integer orderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Wed Nov 01 23:10:42 CST 2017
	 */
	int updateByPrimaryKeySelective(Order record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table orders
	 * @mbg.generated  Wed Nov 01 23:10:42 CST 2017
	 */
	int updateByPrimaryKey(Order record);
}